### ISSUE TITLE
unsupported media type requested

### ISSUE THREAD

**Issue by premkottu** [hashicorp/action-setup-waypoint#284]
We are using github action for waypoint and we are gettin the below error 

Error: Failed to fetch version metadata file Error: unsupported media type requested, only [application/vnd+hashicorp.releases-api.v0+json application/vnd+hashicorp.releases-api.v1+json] are available

Here is the step where we are getting this error.
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Waypoint
        uses: hashicorp/action-setup-waypoint@main
        with:
          version: "0.8.2"
      - run: waypoint init

The same error is happening on the tests on this repo:

https://github.com/hashicorp/action-setup-waypoint/runs/6479406538?check_suite_focus=true

**Comment by rlandingham** [comment]
The weird thing with this issue is that it is very inconsistent for us. It just started a few days agos. Sometimes re-deploying works fine, other times you wait an hour or two. 

I have tried with version 0.7.0 and 0.8.0 ect.

**Comment by MarcMeszaros** [comment]
I also ran into the same issue. I created a fork from the PR for #301 and ~~added the missing `Accept` header~~. Assuming Hashicorp starts accepting PRs. I'll make a proper PR for it. Until then, you can use the fork.

```yaml
- uses: MarcMeszaros/action-setup-waypoint@releases-api
  with:
    version: '0.8.2'
```

**Update: The legacy releases metadata endpoint seems flaky. I re-wrote the install script to use the [new Hashicorp releases API](https://www.hashicorp.com/blog/announcing-the-hashicorp-releases-api).**

**Comment by krantzinator** [comment]
This is not currently actively maintained by the Waypoint team. We may revisit it in the future, but in the interest of clarity, we will archive this project.
