### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by rosscooperman** [hashicorp/action-setup-waypoint#294]
Hasn't received updates in ~2 years, isn't registered in the GitHub Actions Marketplace (so can't be referenced like most other actions) and doesn't appear to work for newer versions of waypoint. I'm sure I can put together an action to install and configure waypoint pretty easily, just wondering if this is considered legacy or what.

![Screen Shot 2022-06-08 at 10 19 52 AM](https://user-images.githubusercontent.com/7132/172640242-ae646711-c2e7-4d60-a568-811524c28684.png)

**Comment by krantzinator** [comment]
This is not currently actively maintained by the Waypoint team. We may revisit it in the future, but in the interest of clarity, we will archive this project.
