### ISSUE TITLE
Action can not install waypoint

### ISSUE THREAD

**Issue by eddumelendez** [hashicorp/action-setup-waypoint#31]
I have the following 

```
- uses: hashicorp/action-setup-waypoint@main
  with:
    version: '0.1.2'
```

and the output is

```
Run hashicorp/action-setup-waypoint@main
  with:
    version: 0.1.2
Error: response does not contain versions. undefined
Error: waypoint version '0.1.2' does not exist
```

looks like it is related to the new release url but it was working fine last weekend. During the wekeend the last successful build for me was with aws url

**Comment by imjohnbo** [comment]
Is it possible the `ncc`-generated `dist` wasn't checked in after updating the release URL? 🙏 

Compare this line in [`dist/index.js`](https://github.com/hashicorp/action-setup-waypoint/blob/main/dist/index.js#L139) to the corresponding one in [`src/index.ts`](https://github.com/hashicorp/action-setup-waypoint/blob/main/src/install.ts#L7) 👀

**Comment by pearkes** [comment]
@imjohnbo Ah yes, thanks for catching that! We should automate that likely...#36.

**Comment by eddumelendez** [comment]
thanks! it is working now!
