### ISSUE TITLE
Warning: The `add-path` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by jritsema** [hashicorp/action-setup-waypoint#41]
I just tried to use this plugin and got this.

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/934927/97499199-d9a67480-1943-11eb-9714-2042cec8bf99.png">

**Comment by pearkes** [comment]
Thanks for reporting, we'll investigate the alternative described there.

**Comment by jacobmammoliti** [comment]
The `add-path` command is now disabled. Actions now errors out.

**Comment by warsameSkew** [comment]
i'm also getting this:
`GitHub Actions has encountered an internal error when running your job.`

**Comment by krantzinator** [comment]
This is not currently actively maintained by the Waypoint team. We may revisit it in the future, but in the interest of clarity, we will archive this project.
